### ISSUE TITLE
first load on ios simulator yields unknown arg type error

### ISSUE THREAD

**Issue by cdaringe** [electrode-io/movies-reloaded-miniapp#8]
# problem

`ern run-ios` produces:

![image](https://user-images.githubusercontent.com/1003261/68823812-c8d4f400-0649-11ea-90be-e4671e17ff8a.png)

# profile

- iPhone 8

```
movies-reloaded-miniapp $ node -v
v13.0.1
movies-reloaded-miniapp $ yarn --version
1.19.1
movies-reloaded-miniapp $ ern --version
 ___ _        _               _       _  _      _   _
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.37.0] [Cauldron: -NONE-]

ℹ ern-local-cli : 0.37.0
child_process.js:642
    throw err;
    ^

Error: Command failed: npm ls -g electrode-native --json
    at checkExecSyncError (child_process.js:603:11)
    at Object.execSync (child_process.js:639:15)
    at showVersion (/Users/c0d01a5/.ern/versions/0.37.0/node_modules/ern-local-cli/src/index.ts:61:5)
    at run (/Users/c0d01a5/.ern/versions/0.37.0/node_modules/ern-local-cli/src/index.ts:179:12)
    at Object.<anonymous> (/Users/c0d01a5/.ern/versions/0.37.0/node_modules/ern-local-cli/src/index.ts:190:3)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
```

# discussion

i'm happy to provide additional diagnostics as requested

**Comment by cdaringe** [comment]
should be fixed by #7
